apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.AppName }}-pv-claim
  namespace: {{ .Values.NameSpace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.MariadbDiskSize }}